// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzKQgd18yX5F9POtVdFcVSLMFMjCTwitY',
    appId: '1:819811720828:web:5a0a47fa551b48a16b73f9',
    messagingSenderId: '819811720828',
    projectId: 'naengmehchu',
    authDomain: 'naengmehchu.firebaseapp.com',
    storageBucket: 'naengmehchu.appspot.com',
    measurementId: 'G-RRHT1HXNXB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDONlryc0BBK1yQ-BFW2jsk0486FMyWU-8',
    appId: '1:819811720828:android:77c80c5b775620cd6b73f9',
    messagingSenderId: '819811720828',
    projectId: 'naengmehchu',
    storageBucket: 'naengmehchu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3qe1YVRBrRcUpoBlvDLTzmk7LzVT12PY',
    appId: '1:819811720828:ios:97aea628ac60bb2a6b73f9',
    messagingSenderId: '819811720828',
    projectId: 'naengmehchu',
    storageBucket: 'naengmehchu.appspot.com',
    iosClientId: '819811720828-as0udcbkbtm6tf572pefdldhqgoef04s.apps.googleusercontent.com',
    iosBundleId: 'com.mju.naengMehChu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3qe1YVRBrRcUpoBlvDLTzmk7LzVT12PY',
    appId: '1:819811720828:ios:6c07638dcde9e1106b73f9',
    messagingSenderId: '819811720828',
    projectId: 'naengmehchu',
    storageBucket: 'naengmehchu.appspot.com',
    iosClientId: '819811720828-kl4mqc7di72ct062imrps9q9jgpt3nie.apps.googleusercontent.com',
    iosBundleId: 'com.example.naengMehChu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzKQgd18yX5F9POtVdFcVSLMFMjCTwitY',
    appId: '1:819811720828:web:ae707346f41b3c776b73f9',
    messagingSenderId: '819811720828',
    projectId: 'naengmehchu',
    authDomain: 'naengmehchu.firebaseapp.com',
    storageBucket: 'naengmehchu.appspot.com',
    measurementId: 'G-00C6SB1Z80',
  );
}
